name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true
      - name: Cache yarn deps
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn install --frozen-lockfile
      - name: Lint
        run: |
          echo "Linting..."
          yarn lint
      - name: Run Tests
        run: |
          echo "Running tests..."
          yarn test
      - name: Build action
        run: |
          echo "Building the github action..."
          yarn build
      - name: Compile
        if: github.ref == 'refs/heads/master'
        run: |
          echo "Compiling the github action..."
          yarn compile
      - name: Release
        if: github.ref == 'refs/heads/master'
        run: |
          echo "Releasing the github action..."
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
